if __name__ == '__main__':
 import getopt
 import cobra
 import math
 import sys
 import os
 import copy
 import json
 import pandas
 import time
 from cobrafunctions.write_spreadsheet import write_spreadsheet
 from cobrafunctions.read_spreadsheets import read_spreadsheets
 from cobrafunctions.cobra_functions import  relax_constraints#, run_qMTA
 from cobrafunctions.ec_base import get_ec_expanded_reaction_mapping, get_net_fluxes_from_ec_model
 from cobrafunctions.weighted_quadratic_flux_minimization import add_quadratic_difference_minimization, update_quadratic_objective_coefficients, update_quadratic_objective_coefficients_cplex, qMTA_get_optimization_target_fluxes_and_weights
 
 
 
 #output_signficant_genes_only=False
 #output_omit_reactions_with_more_than_max_genes=False
 #normalize_by_scale_genes=True#"debug" #Debug =Warning this uses a normalization by flux value
 #normalize_by_scale_unchanged_reactions=True #"debug"
 
 aggregated_file_prefix="fluxes_" #Default output prefix
 log2fc_th=-1 #Default value, all variations will be considered
 min_flux_to_apply_fold_change=1e-6 #Default value, fold change in reactions with less than this flux will not be considered
 target_fold_change_base_weight=1 #Default Value
 min_factor_for_scaling=1e-6 #Default Value
 unchanged_reaction_base_weight=1
 sample_list_file=None #Default, samples will be selected from reaction expression header excluding the first column
 sample_columns=1  #last columm before samples. Irrelevant if sample file is provided
 use_reaction_expression=True #Only True is supported currently
 input_is_log2FC=True
 return_net_fluxes=True
 
 #Solver Paramters
 ##Optlang Paramters. Work with any solver
 solver_qp_methods=["barrier","network","primal"] #will try these methods in order to try to find an optimal solution
 solver_tolerances_feasibility=1e-9
 solver_tolerances_optimality=1e-9
 solver_verbosity=0 #3 is max verbosity
 solver_presolve=True #options are True, False or auto
 #Cplex specific parameters. Only apply to cplex. Optlang lacks binding for these parameters
 cplex_n_threads=1
 cplex_barrier_convergetol=1e-9
 cplex_emphasis_numerical=1
 
  
 """
 run_qMTA.py
 This script runs the quadratic metabolic transformation algorithm (qMTA). qMTA seeks to minimize the difference between the simulated flux distribution and the product of the putative fold changes by the reference flux distribution (target flux) while also minimizing the flux variation from the reference flux distribution in reactions without gene expression fold change. Additionally, both terms are scaled by the difference between the reference flux distribution and the target flux and the reference flux distribution, respectively, to prevent biases towards reactions with high reference flux values. Thus, qMTA can identify the flux map most consistent with gene expression fold changes starting from a reference flux distribution and compute personalized flux maps.
 Usage run_qMTA.py [INPUTS...] 
 
 INPUTS:
 -i, --imputed_reaction_fold_change : Path to the reaction_expression CSV file containing the putative reaction activity fold changes for each individual generated by the map_expression_to_reactions.py script.
 -f, --reference_flux_json : Path to the json file with the average flux distributions for all reactions in all analysed organs. It is generated by the gim3e_and_sampling.py script.
 -m, --organ_specific_gim3e_model : Organ-specific model constrained to the GIM3E flux ranges generated by the gim3e_and_sampling.py script.
 -o, --working_directory : Output and Working directory. Will be created if it does not exist.
 -a, --output_prefix : Optional, prefix added to the output
 -s, --sample_list : Optional, list of sample/individual IDs that should be analysed. If not provided all samples will be analysed. Each row should contain a sample/individuals ID.
 -w, --min_flux_weight: Optional, minimum value allowed for the flux normalization. Default is 1e-6. Lower values give more weight to reactions with low reference flux values.
 -c, --min_flux_fold_change Optional, minimum flux to consider reaction activity fold changes relevant. Putative reaction activity fold changes for reactions under this threshold will be ignored. Default is 1e-6.  
 -r, --unchanged_reaction_weight : Optional, weight given to the minimization of reactions without imputed gene expression data. Default is 1. Lower values will allow more variation in such reactions.  
 -t, --organ_name : Optional, Organ or tissue to be analysed. It should match  the organ name used in both gim3e_and_sampling.py and map_expression_to_reactions.py. If it is not provided, it will take the organ name from the organ_specific_gim3e_model file name. 
 
 OUTPUTS:
 Personalized fluxes file: CSV with the organ-specific personalized flux values computed for each individual. 
 """
 
 sample_list_file=None
 tissue_prefix_defined_flag=False
 gene_str="id"
 gz=False
 #print(sys.argv[1:])
 opts, args = getopt.getopt(sys.argv[1:],"s:m:o:w:r:f:i:a:c:t:z",["sample_list=","organ_specific_gim3e_model=","working_directory=","min_flux_weight=","unchanged_reaction_weight=","reference_flux_json=","output_prefix=","min_flux_fold_change=","imputed_reaction_fold_change=","organ_name=","gz"])
 
 for opt, arg in opts:
      #print opt,arg
      if opt in ("-s", "--sample_list"):
         sample_list_file = arg
      elif opt in ("-m", "--organ_specific_gim3e_model"):
          sbml_file= arg
          if not tissue_prefix_defined_flag:
            tissue_prefix=os.path.basename(sbml_file).replace("_gim3e__restricted_model","").replace("_gim3e__constrained_model","").replace(".SBML","").replace(".XML","").replace(".sbml","").replace(".xml","")
      elif opt in ("-o", "--working_directory"):
          output_folder= arg
          if not os.path.exists(output_folder):
             os.makedirs(output_folder)
          os.chdir(output_folder)
      elif opt in ("-w", "--min_factor_for_scaling"):
         min_factor_for_scaling=float(arg)
      elif opt in ("-r", "--unchanged_reaction_base_weight"):
         unchanged_reaction_base_weight=float(arg)
      elif opt in ("-f", "--reference_flux_json"):
         sampling_fname=arg
      elif opt in ("-i", "--imputed_reaction_fold_change"):
         differential_gene_file=arg
      elif opt in ("-a", "--output_prefix"):
         aggregated_file_prefix=arg
      elif opt in ("-c", "--min_flux_fold_change"):
         min_flux_to_apply_fold_change = float(arg)
      elif opt in ("-t", "--organ_name"):
          tissue_prefix= arg
          tissue_prefix_defined_flag=True 
      elif opt in ("-z", "--gz"):
         gz=True
 
 
 
 print("################################################input")
 
 print(output_folder)
 print(min_flux_to_apply_fold_change)
 print(min_factor_for_scaling)
 print(target_fold_change_base_weight)
 print(differential_gene_file)
 print(log2fc_th)
 print(aggregated_file_prefix)
 print(sample_list_file)
 print(use_reaction_expression)
 
 
 #Default gene parameters
 #gene_parameters={"log2_str":None,"log2_factor":1,"padj_str":"dummy","p_th":1,"log2fc_th":log2fc_th,"gene_str":gene_str,"p_weight_formula":"1","ignore_p_value":True}
 source_condition=tissue_prefix
 source_model=base_model=target_model=cobra.io.read_sbml_model(sbml_file)
 
 
 
 #Replace genes by reaction names if we ere mapping reactions
 if use_reaction_expression:
   for x in source_model.reactions:
      if len(x.genes)>0:
       reaction_id=x.id
       x.gene_reaction_rule=reaction_id.replace("[","_").replace("]","_").replace("]","_").replace("feeding_","").replace("fasting_","")
 
 with open(sampling_fname,"r") as f:
    sampling_dict=json.load(f)
 
 vref_dict={x:sampling_dict[source_condition][x]["mean"] for x in sampling_dict[source_condition]}
 
 max_vref=max(abs(vref_dict[x]) for x in vref_dict)
 relax_constraints(target_model,10,max_vref*1.5)
 
 #Make sure output directory exist
 
 if not os.path.exists(output_folder):
    os.makedirs(output_folder)
 
 os.chdir(output_folder)
 if os.path.isfile(aggregated_file_prefix+tissue_prefix+"_personalized_fluxes.csv") or os.path.isfile(aggregated_file_prefix+tissue_prefix+"_personalized_fluxes.csv.gz"):
   print("Output already exists, stopping script")
   quit()  
 
 
 
 if sample_list_file!=None:
   samples=read_spreadsheets(sample_list_file)
   samples=samples[list(samples.keys())[0]]
   #Assume samples are in rows
   samples=[row[0] for row in samples]
   reaction_data=pandas.read_csv(differential_gene_file,usecols=["id"]+samples)
 else:
    #sheet_name=list(differential_gene_sheet.keys())[0]
    reaction_data=pandas.read_csv(differential_gene_file)
    names_to_omit=["dummy","",None,"V1","id"]
    samples=[x for x in reaction_data.columns if x not in names_to_omit]
 
 print("samples selected", len(samples))
 #Set reaction to index
 reaction_data.set_index(reaction_data.columns[0],inplace=True)
 #Convert to Fold Change if appropiate
 if input_is_log2FC:
    reaction_data[samples]=2**reaction_data[samples]
    print("Converting to linear scale") 
 reaction_list=[x.id for x in target_model.reactions]
 #Get Mapping Dict 
 expanded_reaction_mapping_dict, _ = get_ec_expanded_reaction_mapping(
            target_model, 
            reverse_reaction_pattern="_REV", 
            isoenzyme_reaction_pattern="_EXP_\\d+",
            patterns_to_ommit=["^usage_prot_"],
            verbose=True
        )
 
 #############
 output_data=[]
 processed_samples=[]
 n_samples=len(samples)
 for n,sample in enumerate(samples):
    print("progress",n,"out of",n_samples, sample)
    sample_reaction_fold_changes=reaction_data[[sample]].to_dict()[sample]
    #Get Optimization Targets and Weights
    start_time=time.time()
    optimization_target_fluxes, optimization_target_fluxes_weights=qMTA_get_optimization_target_fluxes_and_weights(
        reference_fluxes=vref_dict,
        model=None,
        target_net_flux_fold_change=sample_reaction_fold_changes,
        target_measured_flux=None, #Not used 
        fold_change_weight=None,#All reactions have same weight
        target_measured_flux_weight=None,#Not used
        fluxes_to_omit=None,
        target_fold_change_base_weight=target_fold_change_base_weight,
        target_measured_flux_base_weight=1,#Not used
        unchanged_reaction_base_weight=unchanged_reaction_base_weight,
        fold_change_is_Log2=False,
        reference_fluxes_are_net_fluxes=True,
        max_Log2FC_change=None, #max_fold_change
        scale_target_fold_change_weight_by_target_flux_difference=True, #normalize_by_scale_genes
        scale_measured_target_flux_weight_by_target_flux_difference=False, #normalize_by_scale_mets
        scale_unchanged_reactions_by_reference_flux=True, #normalize_by_scale_unchanged_reactions
        min_factor_for_scaling=min_factor_for_scaling, #min_flux4weight
        min_flux_to_apply_fold_change=min_factor_for_scaling, #min_flux_fold_change
        precision=None, #Not rounding the weights allows to simplify the unchanged fluxes non-quadratic term to 2
        expanded_reaction_mapping_dict=expanded_reaction_mapping_dict,
        verbose=False
        )
    time1=time.time()
    if(n==0):
      #Set Model
      print("Set Model")
      qp_model,optimized_fluxes=add_quadratic_difference_minimization(target_model, target_fluxes=optimization_target_fluxes,target_fluxes_weight=optimization_target_fluxes_weights,expanded_reaction_mapping_dict=expanded_reaction_mapping_dict,copy_model=True,scaling_factor=1,verbose=False) 
      #Check that all target fluxes are acually optimized
      #Otherwise update will fail
      missing_fluxes=set(optimization_target_fluxes)-set(optimized_fluxes)
      if(len(missing_fluxes)>1):
          raise Exception("Blocked reactions could not be optimized. Please remove them from the model "+", ".join(missing_fluxes))
      #Set Solver Parameters
      ##Set Optlang Parameters
      qp_model.solver.configuration.qp_method=solver_qp_methods[0]
      qp_model.solver.configuration.tolerances.feasibility=solver_tolerances_feasibility
      qp_model.solver.configuration.tolerances.optimality=solver_tolerances_optimality
      qp_model.solver.configuration.verbosity=solver_verbosity
      qp_model.solver.configuration.presolve=solver_presolve
      #Get current_solver
      current_solver = cobra.util.solver.interface_to_str(qp_model.problem)
      print("Current Solver is "+current_solver)
      if 'cplex' in current_solver.lower():
        solver_is_cplex=True
        qp_model.solver.problem.parameters.threads.set(cplex_n_threads)
        qp_model.solver.problem.parameters.emphasis.numerical.set(cplex_emphasis_numerical)
        qp_model.solver.problem.parameters.barrier.convergetol.set(cplex_barrier_convergetol)   
      else:
        solver_is_cplex=False
    #update existing model. For consistency we will also run it at n=0  
    if solver_is_cplex:
        #Updating the cplex problem is faster than using the optlang interface
        qp_model=update_quadratic_objective_coefficients_cplex(model=qp_model,target_fluxes=optimization_target_fluxes,target_fluxes_weight=optimization_target_fluxes_weights,verbose=False,scaling_factor=1)
    else:  
        qp_model=update_quadratic_objective_coefficients(model=qp_model,target_fluxes=optimization_target_fluxes,target_fluxes_weight=optimization_target_fluxes_weights,verbose=False,scaling_factor=1)
    #Solve model
    time2=time.time()
    for solver_qp_method in solver_qp_methods:
        if qp_model.solver.configuration.qp_method!=solver_qp_method:
           qp_model.solver.configuration.qp_method=solver_qp_method
        sol=qp_model.optimize()
        status=sol.status
        if status=="optimal":
           break
        print("\t Objective Value:"+str(sol.objective_value)+" "+sol.status+" with "+solver_qp_method)
    time3=time.time()
    print("Objective Value:"+str(sol.objective_value)+" "+sol.status+" (method: "+solver_qp_method+"); Time to set targets & weights: ",round(time1-start_time,2),"s. Time to update model:", round(time2-time1,2),"s. Time to solve:", round(time3-time2,2),"s. Total:", round(time3-start_time,2),"s.")
    if status=="optimal":
       output_data.append(sol.fluxes)
       processed_samples.append(sample)
    else:
        print(sample+" is not optimal: "+str(status))
        f=open(aggregated_file_prefix+"_samples_without_optimal_solution.txt","a")
        f.write(sample+"\n")
        f.close()

 output_data = pandas.DataFrame(output_data)
 output_data.index = processed_samples  # Setting row names
 #output_data.columns = reaction_list    # Setting column names
 #Calculate net fluxes
 if return_net_fluxes:
    print("Computing Net Fluxes") 
    output_data=get_net_fluxes_from_ec_model(target_model,output_data,output_flux_breakdown=False,ec_expanded_reaction_mapping_dict=expanded_reaction_mapping_dict,minimal_output=True)
 
 
 ######Write output
 out_name=aggregated_file_prefix+tissue_prefix+"_personalized_fluxes.csv"
 if(gz): 
   out_name+=".gz"
 output_data.to_csv(out_name,index_label="sample")       
